- name: Build
        run: bun run build

      # Copia o fallback usando a pasta correta do TanStack
      - name: Create 404 fallback
        run: cp .output/public/index.html .output/public/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.output/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
